# TODO: refine dependencies to ensure Python 3.6 support. Assigments validation is done with Python 3.6

FROM debian:latest

RUN apt-get update && apt-get install -y \
    wget \
    build-essential \
    libssl-dev \
    libffi-dev \
    gcc \
    libxml2-dev \
    libxslt-dev \
    git-all 

RUN apt-get install -y \
    python3.11 \
    python3.11-venv \
    python3.11-dev
    
RUN apt-get clean \
    && rm -rf /var/lib/apt/lists/*

RUN update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.11 1

COPY requirements.txt /app/requirements.txt

RUN python3 -m venv /app/venv-fcnd \
    && . /app/venv-fcnd/bin/activate \
    && pip install --upgrade pip 

# make venv-fcnd to be activated by default
RUN echo "/app/venv-fcnd/bin/activate" >> ~/.bashrc


CMD ["bash"]